using System;
using System.Collections.Generic;
using UnityEngine;

namespace Voxelwild.World.Props
{
    /// <summary>
    /// The prop art: per variant its LOD meshes with their materials, and yaw-independent extents.
    /// Generated by Voxelwild ▸ Art ▸ Build Prop Library from Assets/Art/Models/props_manifest.json
    /// (tools/blender/build_props.py writes the manifest and the FBX files).
    /// </summary>
    [CreateAssetMenu(menuName = "Voxelwild/Prop Library", fileName = "PropLibrary")]
    public sealed class PropLibrary : ScriptableObject
    {
        [Serializable]
        public sealed class Lod
        {
            public Mesh mesh;
            [Tooltip("One per submesh, in submesh order (decimation can change a LOD's submesh layout).")]
            public Material[] materials = Array.Empty<Material>();
        }

        [Serializable]
        public sealed class Entry
        {
            public string name;
            public string kind;
            public int variant;
            public Lod[] lods = Array.Empty<Lod>();
            [Tooltip("Largest horizontal distance of the mesh from its pivot (m).")]
            public float radius;
            [Tooltip("Highest point above the pivot (m).")]
            public float top;
            [Tooltip("Lowest point relative to the pivot (m); negative below it.")]
            public float bottom;
            public bool hang;

            /// <summary>How far the prop reaches from its pivot along its growth direction (formations).</summary>
            public float Length => hang ? -bottom : top;
        }

        public Entry[] entries = Array.Empty<Entry>();

        Entry[][] _byKind;

        /// <summary>Variants of each registry kind, indexed [kind][variant]; missing variants are null.</summary>
        public Entry[][] ByKind
        {
            get
            {
                if (_byKind == null) Index();
                return _byKind;
            }
        }

        void OnEnable() => _byKind = null;
        void OnValidate() => _byKind = null;

        void Index()
        {
            var lists = new List<Entry>[PropRegistry.Count];
            foreach (var e in entries)
            {
                int kind = PropRegistry.Find(e.kind);
                if (kind < 0 || e.lods.Length == 0 || e.lods[0]?.mesh == null) continue;
                var list = lists[kind] ??= new List<Entry>();
                while (list.Count <= e.variant) list.Add(null);
                list[e.variant] = e;
            }
            _byKind = new Entry[PropRegistry.Count][];
            for (int k = 0; k < lists.Length; k++) _byKind[k] = lists[k]?.ToArray() ?? Array.Empty<Entry>();
        }
    }
}
